<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="lazerbot">

    <!-- Constants for wheel mechanical parameters -->
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="chassis_mass" value="0.574"/>
    <xacro:property name="chassis_height" value="0.04"/>
    <xacro:property name="robot_height" value="0.053"/>
    <xacro:property name="wheel_mass" value="0.105" />
    <xacro:property name="wheel_radius" value="0.0508" />
    <xacro:property name="motor_shaft_radius" value="0.002" />
    <xacro:property name="shaft_mass" value="0.001" />

    <!-- The sum of the chassis radius, half the wheel thickness, and the 
    motor shaft length must be equal to the robot radius L = 0.1 m used in the
    kinematic model -->
    <xacro:property name="chassis_radius" value="0.085"/>
    <xacro:property name="wheel_thickness" value="0.01905" />
    <xacro:property name="motor_shaft_length" value="0.005475"/>

    <xacro:include filename="$(find lazerbot_description)/urdf/wheel.urdf.xacro"/>
    <xacro:include filename="$(find lazerbot_description)/urdf/materials.urdf.xacro"/>
    <xacro:include filename="$(find lazerbot_description)/urdf/gazebo.urdf.xacro"/>
    <xacro:include filename="$(find lazerbot_description)/urdf/arm.gazebo" />
    <xacro:include filename="$(find lazerbot_description)/urdf/ros2_control.urdf.xacro"/>
    <xacro:include filename="$(find lazerbot_description)/urdf/arm.xacro"/>

    
    <link name="base_link"></link>

    <joint name="base_link_joint" type="fixed">
        <origin xyz="0 0 ${robot_height}" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="chassis_link" />
    </joint>

    <link name="chassis_link">
        <visual name="">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${chassis_radius}" length="${chassis_height}"/>
            </geometry>
            <material name="black"/>
        </visual>

        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${chassis_radius}" length="${chassis_height}"/>
            </geometry>
            <material name="black"/>
        </collision>

        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="${chassis_mass}"/>
            <inertia ixx="0.00316977667"
                        ixy="0.0"
                        ixz="0.0"
                        iyy="0.00316977667"
                        iyz="0.0"
                        izz="0.005903752"/>
        </inertial>
    </link>
        <xacro:wheel parent="chassis_link" suffix="0" theta="0"/>
        <xacro:wheel parent="chassis_link" suffix="1" theta="${PI/2}"/>
        <xacro:wheel parent="chassis_link" suffix="2" theta="${PI}"/>
        <xacro:wheel parent="chassis_link" suffix="3" theta="${3*PI/2}"/>
        <xacro:arm parent_link="chassis_link"/>

    <link name="camera_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.004 0.004 0.003"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>

    <joint name="camera_joint" type="fixed">
        <!-- спереди робота, чуть выше шасси -->
        <origin xyz="0.1 0 ${chassis_height/2 + 0.07}" rpy="0 0 0"/>
        <parent link="chassis_link"/>
        <child link="camera_link"/>
    </joint>

    <link name="thermal_camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.004 0.004 0.003"/>
      </geometry>
      <material name="red"/>
    </visual>
    </link>

    <joint name="thermal_camera_joint" type="fixed">
        <origin xyz="0.1 0 ${chassis_height/2 + 0.05}" rpy="0 0 0"/>
        <parent link="chassis_link"/>
        <child link="thermal_camera_link"/>
    </joint>

    <link name="lidar_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.003" length="0.003"/>
            </geometry>
            <material name="grey"/>
        </visual>
    </link>

    <joint name="lidar_joint" type="fixed">
        
        <origin xyz="0.1 0 ${chassis_height/2 + 0.06}" rpy="0 0 0"/>
        <parent link="chassis_link"/>
        <child link="lidar_link"/>
    </joint>
</robot>
