<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:macro name="inertial_cylinder" params="mass length radius *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia 
                ixx="${(1/12) * mass * (3*radius*radius + length*length)}"
                ixy="0.0"
                ixz="0.0"
                iyy="${(1/12) * mass * (3*radius*radius + length*length)}"
                iyz="0.0"
                izz="${(1/2) * mass * (radius*radius)}" />
            </inertial>
    </xacro:macro>



    <xacro:macro name="wheel" params="parent suffix theta">
        <joint name="wheel${suffix}_shaft_joint" type="fixed">
            <origin xyz="${chassis_radius*cos(theta)} ${chassis_radius*sin(theta)} 0.0" rpy="0.0 ${PI/2} ${theta+PI}"/>
            <parent link="${parent}"/>
            <child link="motor${suffix}_shaft_link"/>
        </joint>

        <link name="motor${suffix}_shaft_link">
            <visual>
                <origin xyz="0.0 0.0 -${motor_shaft_length/2}" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${motor_shaft_radius}" length="${motor_shaft_length}"/>
                </geometry>
                <material name="red"/>
            </visual>

            <collision>
                <origin xyz="0.0 0.0 -${motor_shaft_length/2}" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${motor_shaft_radius}" length="${motor_shaft_length}"/>
                </geometry>
            </collision>
            <xacro:inertial_cylinder mass="${shaft_mass}" radius="${motor_shaft_radius}" length="${motor_shaft_length}">
                <origin xyz="0.0 0.0 -${motor_shaft_length/2}" rpy="0.0 0.0 0.0"/>
            </xacro:inertial_cylinder>
        </link>

        <joint name="wheel${suffix}_joint" type="continuous">
            <origin xyz="0.0 0.0 -${motor_shaft_length+wheel_thickness/2}" rpy="0.0 0.0 0.0"/>
            <parent link="motor${suffix}_shaft_link"/>
            <child link="wheel${suffix}_link"/>
            <axis xyz="0.0 0.0 -1.0"/>
        </joint>

        <link name="wheel${suffix}_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <mesh filename="file://$(find lazerbot_description)/meshes/rim.stl"/>
                </geometry>
                <material name="grey"/>
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <mesh filename="file://$(find lazerbot_description)/meshes/wheel-collision.dae"/>
                </geometry>
            </collision>

            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <mass value="0.113"/>
                <inertia ixx="0.000089064"
                         ixy="0.0"
                         ixz="0.0"
                         iyy="0.000089064"
                         iyz="0.0"
                         izz="0.000173339"/>
            </inertial>
        </link>

    </xacro:macro>
</robot>
